title: Cuis Smalltalk

description: "Cuis is a free Smalltalk-80 environment with a specific set of goals: being simple and powerful. It is also portable to any platform, fast and efficient."
#author: "Jorge Sanz"

theme: minima

base_url: /Cuis-Website

# Minima social links
#twitter_username: Cuis-Smalltalk
github_username: Cuis-Smalltalk
#linkedin_username: Cuis-Smalltalk
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/documentation.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
