title: Cuis Smalltalk
description: "The modern Smalltalk-80"
author: "Copyright © 2009-2026 Juan Vuletich"

theme: null

sass:
  sourcemap: development

plugins:
  - jekyll-feed
  - jekyll-seo-tag

date_format: "%Y-%m-%d"

kramdown:
  toc_levels: [2]

collections:
  docs:
    output: true
    permalink: /documentation/:path

defaults:
  - scope:
      type: posts
    values:
      window: senders
  - scope:
      type: docs
    values:
      layout: doc
      window: workspace

header_pages:
  - _pages/frontpage.md
  - _pages/overview.md
  - _pages/documentation.md
  - _pages/stories.md
  - _pages/news.md
  - _pages/community.md
  - _pages/packages.md

include:
  - _pages

exclude:
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
